permissions:
  contents: write

name: Deploy Pure HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Pure HTML folder
        run: |
          # 创建临时目录并复制 Pure HTML 文件夹内容
          mkdir temp-deploy
          cp -r "Pure HTML"/* temp-deploy/
          cd temp-deploy

          # 初始化 Git 仓库并设置分支为 main
          git init -b main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 添加文件并提交更改
          git add .
          git commit -m "Deploy Pure HTML folder"

          # 推送到远程 gh-pages 分支，创建分支如果不存在
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
